let data = [
    {
        id : 0,
        name : "동아리1",
        category : "문화",
        description : "문화 카테고리의 동아리1입니다.",
        yearOfCreate : "2001년",
        clubPresident : "안유진",
        PhoneNumber : "010-1111-1111",
    },
    {
        id : 1,
        name : "동아리2",
        category : "봉사",
        description : "봉사 카테고리의 동아리2입니다.",
        yearOfCreate : "2002년",
        clubPresident : "김채원",
        PhoneNumber : "010-1111-1111",
    },
    {
        id : 2,
        name : "동아리3",
        category : "학술",
        description : "학술 카테고리의 동아리3입니다.",
        yearOfCreate : "2003년",
        clubPresident : "강혜원",
        PhoneNumber : "010-1111-1111",
    },
    {
        id : 3,
        name : "동아리4",
        category : "창업",
        description : "창업 카테고리의 동아리4입니다.",
        yearOfCreate : "2004년",
        clubPresident : "조유리",
        PhoneNumber : "010-1111-1111",
    },
    {
        id : 4,
        name : "동아리5",
        category : "어학",
        description : "어학 카테고리의 동아리5입니다.",
        yearOfCreate : "2005년",
        clubPresident : "혼다 히토미",
        PhoneNumber : "010-1111-1111",
    },
    {
        id : 5,
        name : "동아리6",
        category : "체육",
        description : "체육 카테고리의 동아리6입니다.",
        yearOfCreate : "2006년",
        clubPresident : "김민주",
        PhoneNumber : "010-1111-1111",
    },
    {
        id : 6,
        name : "동아리7",
        category : "친목",
        description : "친목 카테고리의 동아리7입니다.",
        yearOfCreate : "2007년",
        clubPresident : "장원영",
        PhoneNumber : "010-1111-1111",
    },
]

export {data};